name: Burns Baxter
favicon: null
layout_spectrum: 0.7334091083612293
typography_spectrum: 0.2611477756872773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5364320429507643
  lightness: 0.7736660544760525
  saturation: 0.0773195899091661
  rhythmicContrast: 0.225458902772516
purpose: []
